theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "multiple"
 
[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'
 
[editor.whitespace]
render = 'all'
characters = { newline = '¬' }
 
[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
 
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
 
[keys.insert.j]
k = "normal_mode"

