theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "multiple"
 
[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'
 
[editor.whitespace]
render = 'all'
characters = { newline = '¬' }
 
[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
 
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"S-l" = "goto_next_buffer"
"S-h" = "goto_previous_buffer"
"C-s" = ":w"
"ret" = ["open_below", "normal_mode"]
# move lines up/down
"C-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"C-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[keys.insert]
j = { k = "normal_mode" }
left = "no_op"
right = "no_op"
up = "no_op"
down = "no_op"

[keys.normal.space]
# copy current file path to system clipboard
"C-f" = "copy_between_registers"
