# introduce new language server
[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20     # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true         # completions will return before snippets by default
feature_words = true          # enable completion by word
feature_snippets = true       # enable snippets
feature_unicode_input = true  # enable "unicode input"
feature_paths = true          # enable path completion

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
validate = "on"
rulesCustomizations = []
run = "onType"
nodePath = ""
quiet = false
experimental = { useFlatConfig = true }
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
problems = { shortenToSingleLine = false }
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--write"] }

[[language]]
name = "typescript"
auto-format = true
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls"]
# formatter = { command = "prettier", args = ["--plugin", "prettier-plugin-astro", "--parser", "astro"] }
auto-format = true

[[language]]
name = "vue"
auto-format = false
# formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "htmldjango"
file-types = ["eta"]
language-servers = [ "scls" ]
indent = { unit = "  ", tab-width = 2 }
formatter = { command = "prettier", args = ["--stdin-filepath", "file.eta"] }

[[language]]
name = "cfml"
scope = "source.cfml"
language-servers = [ "scls" ]
file-types = ["cfc"]
comment-tokens = "//"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 2, unit = "\t" }
roots = []

[[grammar]]
name = "cfml"
source = { git = "git@github.com:cfmleditor/tree-sitter-cfml.git", rev = "master", subpath = "cfml" }

[[language]]
name = "cfhtml"
scope = "text.cfhtml"
grammar = "cfml"
language-servers = [ "scls" ]
file-types = ["cfm", "cfml"]
block-comment-tokens = { start = "<!---", end = "--->" }
indent = { tab-width = 2, unit = "\t" }
roots = []

[[language]]
name = "cfscript"
scope = "source.cfscript"
file-types = ["cfs"]
comment-token = "//"
indent = { tab-width = 2, unit = "\t" }
roots = []

[[grammar]]
name = "cfscript"
source = { git = "git@github.com:cfmleditor/tree-sitter-cfml.git", rev = "master", subpath = "cfscript" }

[[grammar]]
name = "cfquery"
source = { git = "git@github.com:cfmleditor/tree-sitter-cfml.git", rev = "master", subpath = "cfquery" }

[[language]]
name = "sql"
file-types = [ "sql" ]

